// 🎯 SYSTÈME DE SYNCHRONISATION ACTIVÉ !
// Modifiez ce fichier et les changements apparaissent automatiquement dans dico.html et index.html
// Testé et validé le $(date)

const questions = {
            facile: [
                {id:"f_1", term:"Mot de passe", question:"Quelle est la meilleure pratique pour un mot de passe ?", questionEn:"What is the best practice for a password?", options:["Utiliser le même pour tous vos comptes", "Créer un mot de passe unique et complexe", "Choisir quelque chose de très simple", "Utiliser votre nom de famille"], optionsEn:["Use the same for all your accounts", "Create a unique and complex password", "Choose something very simple", "Use your last name"], correct:1, explanation:"Utiliser un mot de passe unique et complexe pour chaque compte est crucial. Un gestionnaire de mots de passe est l'outil idéal pour cela.", explanationEn:"Using a unique and complex password for each account is crucial. A password manager is the ideal tool for this."},
                {id:"f_2", term:"Hameçonnage", question:"Un email de votre banque demande de cliquer sur un lien pour vérifier votre compte. Que faire ?", questionEn:"An email from your bank asks you to click on a link to verify your account. What to do?", options:["Cliquer sur le lien pour vérifier", "Contacter sa banque par un autre moyen", "Ignorer l'email et le supprimer", "Répondre à l'expéditeur du mail"], optionsEn:["Click on the link to verify", "Contact the bank by other means", "Ignore the email and delete it", "Reply to the email sender"], correct:1, explanation:"Ne jamais cliquer sur les liens ou utiliser les contacts d'un email suspect. Il faut toujours se connecter à son espace client via le site officiel ou une application connue.", explanationEn:"Never click on links or use contacts from a suspicious email. Always connect to your customer area via the official website or a known application."},
                {id:"f_3", term:"Antivirus", question:"Quelle est la fonction principale d'un antivirus ?", questionEn:"What is the main function of an antivirus?", options:["Nettoyer les fichiers du disque", "Protéger des logiciels malveillants", "Accélérer le démarrage du système", "Sauvegarder les données en ligne"], optionsEn:["Clean up the disk files", "Protect from malicious software", "Speed up the system startup", "Back up the data online"], correct:1, explanation:"L'antivirus protège votre système contre les virus, malwares et autres menaces informatiques.", explanationEn:"Antivirus protects your system against viruses, malware and other computer threats."},
                {id:"f_4", term:"Pare-feu", question:"Qu'est-ce qu'un pare-feu (firewall) ?", questionEn:"What is a firewall?", options:["Une barrière de sécurité réseau", "Un gestionnaire de fichiers local", "Un logiciel de nettoyage de disque", "Un navigateur web très sécurisé"], optionsEn:["A network security barrier", "A local file manager", "A disk cleaning software", "A very secure web browser"], correct:0, explanation:"Un pare-feu contrôle le trafic réseau entrant et sortant selon des règles de sécurité prédéfinies.", explanationEn:"A firewall controls incoming and outgoing network traffic according to predefined security rules."},
                {id:"f_5", term:"Sauvegarde", question:"Pourquoi est-il important de faire des sauvegardes ?", questionEn:"Why is it important to make backups?", options:["Pour économiser de l'espace disque", "Pour accélérer les performances", "Pour protéger ses données importantes", "Pour améliorer la sécurité du Wi-Fi"], optionsEn:["To save some disk space", "To speed up overall performance", "To protect your important data", "To improve Wi-Fi security"], correct:2, explanation:"Les sauvegardes permettent de récupérer vos données en cas de panne, d'attaque ou d'accident.", explanationEn:"Backups allow you to recover your data in case of failure, attack or accident."},
                {id:"f_6", term:"HTTPS", question:"Que signifie la présence de HTTPS dans une URL ?", questionEn:"What does the presence of HTTPS in a URL mean?", options:["Le site web est entièrement gratuit", "Le site web a été certifié sûr", "La connexion au site est chiffrée", "La navigation sur le site est rapide"], optionsEn:["The website is completely free", "The website has been certified safe", "The connection to the site is encrypted", "Browsing on the site is fast"], correct:2, explanation:"HTTPS indique que la communication entre votre navigateur et le site web est chiffrée.", explanationEn:"HTTPS indicates that communication between your browser and the website is encrypted."},
                {id:"f_7", term:"Mise à jour", question:"Pourquoi faut-il maintenir ses logiciels à jour ?", questionEn:"Why should software be kept up to date?", options:["Pour obtenir de nouvelles fonctions", "Pour corriger les failles de sécurité", "Pour économiser la batterie du PC", "Pour améliorer le design graphique"], optionsEn:["To get brand new features", "To fix the security vulnerabilities", "To save the computer's battery", "To improve the graphic design"], correct:1, explanation:"Les mises à jour corrigent souvent des vulnérabilités de sécurité découvertes après la sortie du logiciel.", explanationEn:"Updates often fix security vulnerabilities discovered after software release."},
                {id:"f_8", term:"Wi-Fi public", question:"Quel est le principal risque d'utiliser un Wi-Fi public ?", questionEn:"What is the main risk of using public Wi-Fi?", options:["Consommer son forfait de données", "L'interception de vos données", "Le ralentissement de la connexion", "L'usure rapide de la batterie"], optionsEn:["Consuming your mobile data plan", "The interception of your data", "The slowing down of the connection", "The rapid draining of the battery"], correct:1, explanation:"Les réseaux Wi-Fi publics ne sont souvent pas sécurisés, permettant l'interception des données transmises.", explanationEn:"Public Wi-Fi networks are often unsecured, allowing interception of transmitted data."},
                {id:"f_9", term:"Spam", question:"Qu'est-ce qu'un spam ?", questionEn:"What is spam?", options:["Un type de virus informatique", "Un logiciel de sécurité payant", "Un email non sollicité ou indésirable", "Une sauvegarde de données en ligne"], optionsEn:["A type of computer virus", "A paid security software", "An unsolicited or unwanted email", "An online data backup"], correct:2, explanation:"Le spam désigne les emails non sollicités, souvent publicitaires ou malveillants.", explanationEn:"Spam refers to unsolicited emails, often advertising or malicious."},
                {id:"f_10", term:"Données personnelles", question:"Que sont les données personnelles ?", questionEn:"What is personal data?", options:["Seulement le nom et le prénom", "Juste les données de votre banque", "Toute information vous identifiant", "Uniquement tous vos mots de passe"], optionsEn:["Only the first and last name", "Just your bank account data", "Any information identifying you", "Only all of your passwords"], correct:2, explanation:"Les données personnelles incluent toute information qui permet d'identifier directement ou indirectement une personne.", explanationEn:"Personal data includes any information that can directly or indirectly identify a person."},
                {id:"f_11", term:"Authentification", question:"Qu'est-ce que l'authentification ?", questionEn:"What is authentication?", options:["Vérifier l'identité d'un utilisateur", "Chiffrer des données sensibles", "Supprimer des fichiers inutiles", "Accélérer la vitesse du système"], optionsEn:["Verifying a user's identity", "Encrypting sensitive data", "Deleting unnecessary files", "Speeding up the system"], correct:0, explanation:"L'authentification est le processus qui permet de vérifier qu'un utilisateur est bien celui qu'il prétend être.", explanationEn:"Authentication is the process that verifies that a user is who they claim to be."},
                {id:"f_12", term:"Logiciel malveillant", question:"Qu'est-ce qu'un logiciel malveillant ?", questionEn:"What is malware?", options:["Un programme bénéfique et utile", "Un système d'exploitation mobile", "Un programme conçu pour nuire", "Un navigateur internet sécurisé"], optionsEn:["A beneficial and useful program", "A mobile operating system", "A program designed to harm", "A secure internet browser"], correct:2, explanation:"Un logiciel malveillant (malware) est un programme créé dans l'intention de causer des dommages ou d'accéder illégalement à un système.", explanationEn:"Malware is a program created with the intention of causing damage or illegally accessing a system."},
                {id:"f_13", term:"Chiffrement", question:"À quoi sert le chiffrement ?", questionEn:"What is encryption used for?", options:["Compresser des fichiers volumineux", "Accélérer les transferts de données", "Protéger la confidentialité des données", "Organiser les dossiers du système"], optionsEn:["Compressing large files", "Speeding up data transfers", "Protecting data confidentiality", "Organizing system folders"], correct:2, explanation:"Le chiffrement transforme les données en un format illisible sans la clé appropriée, protégeant ainsi leur confidentialité.", explanationEn:"Encryption transforms data into an unreadable format without the appropriate key, thus protecting their confidentiality."},
                {id:"f_14", term:"Cookie", question:"Qu'est-ce qu'un cookie sur internet ?", questionEn:"What is a cookie on the internet?", options:["Un type de virus informatique", "Une catégorie de spam par email", "Un fichier de suivi de navigation", "Un mot de passe temporaire"], optionsEn:["A type of computer virus", "A category of email spam", "A browsing tracking file", "A temporary password"], correct:2, explanation:"Un cookie est un petit fichier texte stocké par le navigateur pour mémoriser des informations sur votre navigation.", explanationEn:"A cookie is a small text file stored by the browser to remember information about your browsing."},
                {id:"f_15", term:"URL", question:"Qu'est-ce qu'une URL ?", questionEn:"What is a URL?", options:["Un type de virus très répandu", "Un logiciel antivirus populaire", "L'adresse d'une page web", "Un protocole de sécurité réseau"], optionsEn:["A very common type of virus", "A popular antivirus software", "The address of a web page", "A network security protocol"], correct:2, explanation:"Une URL (Uniform Resource Locator) est l'adresse unique qui permet d'accéder à une ressource sur internet.", explanationEn:"A URL (Uniform Resource Locator) is the unique address that allows access to a resource on the internet."},
                {id:"f_16", term:"Téléchargement", question:"Quel est le risque principal lors du téléchargement de fichiers ?", questionEn:"What is the main risk when downloading files?", options:["Consommer trop d'espace disque", "Ralentir fortement son ordinateur", "Installer un malware par accident", "User prématurément sa connexion"], optionsEn:["Consuming too much disk space", "Significantly slowing down a computer", "Installing malware by accident", "Wearing out the connection prematurely"], correct:2, explanation:"Les téléchargements peuvent contenir des logiciels malveillants cachés, il est important de vérifier la source et d'utiliser un antivirus.", explanationEn:"Downloads may contain hidden malware, it's important to check the source and use antivirus."},
                {id:"f_17", term:"Navigation privée", question:"À quoi sert le mode navigation privée ?", questionEn:"What is private browsing mode used for?", options:["Accélérer la vitesse de navigation", "Bloquer l'accès à certains sites", "Ne pas enregistrer son historique", "Chiffrer toutes ses données"], optionsEn:["Speeding up the browsing speed", "Blocking access to certain sites", "Not saving one's browsing history", "Encrypting all of one's data"], correct:2, explanation:"Le mode navigation privée évite d'enregistrer l'historique, les cookies et autres données de navigation sur l'appareil local.", explanationEn:"Private browsing mode avoids saving history, cookies and other browsing data on the local device."},
                {id:"f_18", term:"Pop-up", question:"Qu'est-ce qu'un pop-up suspect ?", questionEn:"What is a suspicious pop-up?", options:["Une fenêtre de conversation en direct", "Un menu de navigation du site", "Une petite fenêtre publicitaire intrusive", "Une boîte de dialogue système"], optionsEn:["A live chat window", "A site navigation menu", "A small intrusive ad window", "A system dialog box"], correct:2, explanation:"Les pop-ups suspects sont souvent utilisés pour diffuser des publicités trompeuses ou des logiciels malveillants.", explanationEn:"Suspicious pop-ups are often used to spread deceptive ads or malware."},
                {id:"f_19", term:"Réseau social", question:"Quelle précaution prendre sur les réseaux sociaux ?", questionEn:"What precaution to take on social networks?", options:["Partager un maximum de photos", "Accepter toutes les demandes d'amis", "Contrôler la visibilité des publications", "Publier son numéro de téléphone"], optionsEn:["Sharing a maximum of photos", "Accepting all friend requests", "Controlling the visibility of posts", "Publishing one's phone number"], correct:2, explanation:"Il est important de contrôler qui peut voir vos publications pour protéger votre vie privée et votre sécurité.", explanationEn:"It's important to control who can see your posts to protect your privacy and security."},
                {id:"f_20", term:"Email suspect", question:"Comment reconnaître un email suspect ?", questionEn:"How to recognize a suspicious email?", options:["Une adresse email très longue", "Fautes d'orthographe et demandes urgentes", "Un texte particulièrement long", "Un email qui contient des images"], optionsEn:["A very long email address", "Spelling mistakes and urgent requests", "A particularly long text", "An email that contains images"], correct:1, explanation:"Les emails suspects contiennent souvent des erreurs de langue et demandent des informations sensibles ou des actions urgentes.", explanationEn:"Suspicious emails often contain language errors and ask for sensitive information or urgent actions."},
                {id:"f_21", term:"Application mobile", question:"Quelle précaution prendre avant d'installer une application mobile ?", questionEn:"What precaution to take before installing a mobile app?", options:["L'installer le plus vite possible", "Accepter tous les termes sans lire", "Vérifier les permissions demandées", "Donner accès à tous les contacts"], optionsEn:["Installing it as fast as possible", "Accepting all terms without reading", "Checking the requested permissions", "Giving access to all contacts"], correct:2, explanation:"Il faut toujours vérifier les permissions demandées par une application et s'assurer qu'elles sont justifiées par ses fonctionnalités.", explanationEn:"Always check the permissions requested by an app and ensure they are justified by its features."},
                {id:"f_22", term:"Code PIN", question:"Qu'est-ce qu'un bon code PIN ?", questionEn:"What is a good PIN code?", options:["Un code simple comme 1234", "Sa propre date de naissance", "Un code difficile à deviner", "Un code facile comme 0000"], optionsEn:["A simple code like 1234", "One's own date of birth", "A code that is hard to guess", "An easy code like 0000"], correct:2, explanation:"Un bon code PIN ne doit pas être évident (éviter 1234, 0000, dates de naissance) et doit rester confidentiel.", explanationEn:"A good PIN should not be obvious (avoid 1234, 0000, birth dates) and must remain confidential."},
                {id:"f_23", term:"Pièce jointe", question:"Que faire avant d'ouvrir une pièce jointe ?", questionEn:"What to do before opening an attachment?", options:["L'ouvrir immédiatement pour voir", "La transférer à tous ses contacts", "Vérifier l'expéditeur et la scanner", "L'enregistrer directement sur le bureau"], optionsEn:["Opening it immediately to see", "Forwarding it to all contacts", "Checking the sender and scanning it", "Saving it directly to the desktop"], correct:2, explanation:"Toujours vérifier l'expéditeur, le contexte et scanner les pièces jointes avec un antivirus avant de les ouvrir.", explanationEn:"Always check the sender, context and scan attachments with antivirus before opening them."},
                {id:"f_24", term:"Connexion sécurisée", question:"Comment s'assurer qu'une connexion est sécurisée ?", questionEn:"How to ensure a connection is secure?", options:["Regarder la couleur du site web", "Compter le nombre de publicités", "Vérifier la présence du cadenas", "Vérifier la vitesse de connexion"], optionsEn:["Looking at the website's color", "Counting the number of ads", "Checking for the padlock icon", "Checking the connection speed"], correct:2, explanation:"Le cadenas dans la barre d'adresse et le protocole HTTPS indiquent que la connexion est chiffrée et sécurisée.", explanationEn:"The padlock in the address bar and HTTPS protocol indicate that the connection is encrypted and secure."},
                {id:"f_25", term:"Vie privée", question:"Pourquoi protéger sa vie privée en ligne ?", questionEn:"Why protect privacy online?", options:["C'est une obligation légale stricte", "Pour accélérer sa navigation web", "Pour éviter l'usurpation d'identité", "Pour économiser de l'argent"], optionsEn:["It is a strict legal obligation", "To speed up one's web browsing", "To avoid identity theft", "To save money"], correct:2, explanation:"Protéger sa vie privée en ligne permet d'éviter l'usurpation d'identité, le ciblage abusif et la manipulation.", explanationEn:"Protecting privacy online helps avoid identity theft, abusive targeting and manipulation."}
            ],
            intermediaire: [
                {id:"i_1", term:"VPN", question:"Quel est l'avantage principal d'un VPN ?", questionEn:"What is the main advantage of a VPN?", options:["Organiser ses favoris web", "Accélérer sa connexion internet", "Chiffrer et anonymiser le trafic", "Bloquer toutes les publicités"], optionsEn:["Organizing web bookmarks", "Speeding up the internet connection", "Encrypting and anonymizing traffic", "Blocking all advertisements"], correct:2, explanation:"Un VPN chiffre vos communications et masque votre adresse IP pour protéger votre vie privée.", explanationEn:"A VPN encrypts your communications and hides your IP address to protect your privacy."},
                {id:"i_2", term:"Double authentification", question:"Qu'est-ce que l'authentification à deux facteurs (2FA) ?", questionEn:"What is two-factor authentication (2FA)?", options:["Utiliser deux comptes différents", "Avoir deux mots de passe pour un compte", "Une sécurité avec double vérification", "Une sauvegarde automatique des données"], optionsEn:["Using two different accounts", "Having two passwords for one account", "Security with double verification", "An automatic data backup"], correct:2, explanation:"La 2FA ajoute une couche de sécurité supplémentaire en demandant un second facteur d'authentification.", explanationEn:"2FA adds an additional layer of security by requiring a second authentication factor."},
                {id:"i_3", term:"SSL/TLS", question:"Que signifie un cadenas dans la barre d'adresse du navigateur ?", questionEn:"What does a padlock in the browser address bar mean?", options:["Le site est protégé par mot de passe", "La page web est en maintenance", "La connexion avec le site est chiffrée", "Le site a été bloqué par un antivirus"], optionsEn:["The site is password protected", "The web page is under maintenance", "The connection with the site is encrypted", "The site has been blocked by an antivirus"], correct:2, explanation:"Le cadenas indique que la connexion est chiffrée avec SSL/TLS, protégeant les données transmises.", explanationEn:"The padlock indicates that the connection is encrypted with SSL/TLS, protecting transmitted data."},
                {id:"i_4", term:"Ransomware", question:"Qu'est-ce qu'un ransomware ?", questionEn:"What is ransomware?", options:["Un système d'exploitation sécurisé", "Un logiciel de sauvegarde de fichiers", "Un malware qui demande une rançon", "Un antivirus gratuit et open source"], optionsEn:["A secure operating system", "A file backup software", "A malware that demands a ransom", "A free and open-source antivirus"], correct:2, explanation:"Un ransomware chiffre vos fichiers et demande une rançon pour les déchiffrer.", explanationEn:"Ransomware encrypts your files and demands a ransom to decrypt them."},
                {id:"i_5", term:"Ingénierie sociale", question:"Qu'est-ce que l'ingénierie sociale en cybersécurité ?", questionEn:"What is social engineering in cybersecurity?", options:["Créer des groupes sur les réseaux", "Développer des applications sociales", "La manipulation psychologique", "Analyser les comportements en ligne"], optionsEn:["Creating groups on social networks", "Developing social applications", "Psychological manipulation", "Analyzing online behaviors"], correct:2, explanation:"L'ingénierie sociale exploite la psychologie humaine pour obtenir des informations confidentielles.", explanationEn:"Social engineering exploits human psychology to obtain confidential information."},
                {id:"i_6", term:"Adresse IP", question:"À quoi sert une adresse IP ?", questionEn:"What is an IP address used for?", options:["Identifier un appareil sur un réseau", "Stocker les mots de passe de manière sûre", "Chiffrer les données de navigation", "Accélérer la connexion au FAI"], optionsEn:["Identifying a device on a network", "Storing passwords securely", "Encrypting browsing data", "Speeding up the ISP connection"], correct:0, explanation:"Une adresse IP est un identifiant unique qui permet de localiser et communiquer avec un appareil sur un réseau.", explanationEn:"An IP address is a unique identifier that allows locating and communicating with a device on a network."},
                {id:"i_7", term:"Certificat numérique", question:"Qu'est-ce qu'un certificat numérique ?", questionEn:"What is a digital certificate?", options:["Un diplôme obtenu en ligne", "Une version premium d'antivirus", "Un document électronique d'identité", "Un logiciel de sauvegarde cloud"], optionsEn:["A degree obtained online", "A premium version of an antivirus", "An electronic identity document", "A cloud backup software"], correct:2, explanation:"Un certificat numérique est un document électronique qui permet d'authentifier l'identité d'une entité sur internet.", explanationEn:"A digital certificate is an electronic document that authenticates the identity of an entity on the internet."},
                {id:"i_8", term:"DNS", question:"Que fait le système DNS ?", questionEn:"What does the DNS system do?", options:["Il bloque les virus des sites web", "Il chiffre les emails envoyés", "Il traduit les noms de domaine en IP", "Il compresse les fichiers pour le web"], optionsEn:["It blocks viruses from websites", "It encrypts sent emails", "It translates domain names into IPs", "It compresses files for the web"], correct:2, explanation:"Le DNS (Domain Name System) traduit les noms de domaine lisibles en adresses IP que les ordinateurs comprennent.", explanationEn:"DNS (Domain Name System) translates readable domain names into IP addresses that computers understand."},
                {id:"i_9", term:"Hachage", question:"À quoi sert le hachage en sécurité ?", questionEn:"What is hashing used for in security?", options:["Compresser des fichiers texte", "Accélérer les téléchargements", "Vérifier l'intégrité d'un fichier", "Organiser les dossiers système"], optionsEn:["Compressing text files", "Speeding up downloads", "Verifying a file's integrity", "Organizing system folders"], correct:2, explanation:"Le hachage produit une empreinte unique d'un fichier, permettant de détecter toute modification.", explanationEn:"Hashing produces a unique fingerprint of a file, allowing detection of any modification."},
                {id:"i_10", term:"Proxy", question:"Quel est le rôle d'un serveur proxy ?", questionEn:"What is the role of a proxy server?", options:["Stocker des fichiers en cache", "Chiffrer les mots de passe locaux", "Servir d'intermédiaire de connexion", "Nettoyer le système d'exploitation"], optionsEn:["Storing files in a cache", "Encrypting local passwords", "Acting as a connection intermediary", "Cleaning the operating system"], correct:2, explanation:"Un proxy sert d'intermédiaire entre votre appareil et internet, pouvant filtrer ou masquer votre adresse IP.", explanationEn:"A proxy acts as intermediary between your device and the internet, potentially filtering or hiding your IP address."},
                {id:"i_11", term:"Keylogger", question:"Qu'est-ce qu'un keylogger ?", questionEn:"What is a keylogger?", options:["Un gestionnaire de mots de passe", "Un antivirus pour les claviers", "Un logiciel espion de frappes", "Un système de sauvegarde cloud"], optionsEn:["A password manager", "An antivirus for keyboards", "A keystroke spying software", "A cloud backup system"], correct:2, explanation:"Un keylogger enregistre secrètement tout ce qui est tapé au clavier, permettant de voler mots de passe et informations sensibles.", explanationEn:"A keylogger secretly records everything typed on the keyboard, allowing theft of passwords and sensitive information."},
                {id:"i_12", term:"Sandbox", question:"Qu'est-ce qu'une sandbox en sécurité informatique ?", questionEn:"What is a sandbox in computer security?", options:["Un bac à sable pour enfants", "Un type de virus informatique", "Un environnement d'exécution isolé", "Un jeu vidéo éducatif sur la sécurité"], optionsEn:["A sandbox for children", "A type of computer virus", "An isolated execution environment", "An educational video game on security"], correct:2, explanation:"Une sandbox est un environnement sécurisé et isolé où l'on peut exécuter des programmes suspects sans risquer le système principal.", explanationEn:"A sandbox is a secure and isolated environment where suspicious programs can be run without risking the main system."},
                {id:"i_13", term:"Signature numérique", question:"À quoi sert une signature numérique ?", questionEn:"What is a digital signature used for?", options:["Dessiner sa signature sur un PC", "Compresser des fichiers signés", "Authentifier l'origine d'un document", "Accélérer les transferts de fichiers"], optionsEn:["Drawing one's signature on a PC", "Compressing signed files", "Authenticating a document's origin", "Speeding up file transfers"], correct:2, explanation:"Une signature numérique permet de vérifier l'authenticité et l'intégrité d'un document électronique.", explanationEn:"A digital signature verifies the authenticity and integrity of an electronic document."},
                {id:"i_14", term:"Port réseau", question:"Qu'est-ce qu'un port en réseau informatique ?", questionEn:"What is a port in computer networking?", options:["Un connecteur physique pour câble", "Un type de câble réseau spécial", "Un point d'accès logique pour service", "Un logiciel de gestion de connexion"], optionsEn:["A physical connector for a cable", "A special type of network cable", "A logical access point for a service", "A connection management software"], correct:2, explanation:"Un port réseau est un point d'accès logique qui permet à différents services de communiquer sur le même appareil.", explanationEn:"A network port is a logical access point that allows different services to communicate on the same device."},
                {id:"i_15", term:"MAC Address", question:"Qu'est-ce qu'une adresse MAC ?", questionEn:"What is a MAC address?", options:["L'adresse d'un ordinateur Apple", "Un virus qui cible les Mac", "L'identifiant physique d'une carte réseau", "Un protocole de sécurité d'Apple"], optionsEn:["The address of an Apple computer", "A virus that targets Macs", "The physical identifier of a network card", "An Apple security protocol"], correct:2, explanation:"L'adresse MAC (Media Access Control) est un identifiant unique attribué à chaque interface réseau.", explanationEn:"MAC (Media Access Control) address is a unique identifier assigned to each network interface."},
                {id:"i_16", term:"Token", question:"Qu'est-ce qu'un token de sécurité ?", questionEn:"What is a security token?", options:["Une pièce dans un jeu vidéo", "Un type de logiciel malveillant", "Un jeton numérique d'authentification", "Un antivirus pour les professionnels"], optionsEn:["A coin in a video game", "A type of malicious software", "A digital authentication token", "An antivirus for professionals"], correct:2, explanation:"Un token est un jeton numérique temporaire utilisé pour l'authentification et l'autorisation sécurisées.", explanationEn:"A token is a temporary digital token used for secure authentication and authorization."},
                {id:"i_17", term:"CAPTCHA", question:"À quoi sert un CAPTCHA ?", questionEn:"What is a CAPTCHA used for?", options:["Accélérer la navigation sur un site", "Chiffrer les données d'un formulaire", "Distinguer les humains des robots", "Compresser les images d'une page"], optionsEn:["Speeding up browsing on a site", "Encrypting data in a form", "Distinguishing humans from bots", "Compressing images on a page"], correct:2, explanation:"Un CAPTCHA est un test conçu pour être facile pour les humains mais difficile pour les programmes automatisés.", explanationEn:"A CAPTCHA is a test designed to be easy for humans but difficult for automated programs."},
                {id:"i_18", term:"Vulnérabilité", question:"Qu'est-ce qu'une vulnérabilité informatique ?", questionEn:"What is a computer vulnerability?", options:["Un logiciel qui est devenu très lent", "Un fichier qui a été corrompu", "Une faiblesse exploitable d'un système", "Une connexion internet instable"], optionsEn:["A software that has become very slow", "A file that has been corrupted", "An exploitable weakness in a system", "An unstable internet connection"], correct:2, explanation:"Une vulnérabilité est une faiblesse dans un système qui peut être exploitée par des attaquants pour compromettre la sécurité.", explanationEn:"A vulnerability is a weakness in a system that can be exploited by attackers to compromise security."},
                {id:"i_19", term:"Patch", question:"Qu'est-ce qu'un patch de sécurité ?", questionEn:"What is a security patch?", options:["Un autocollant décoratif pour PC", "Un tout nouveau logiciel à installer", "Une correction pour un logiciel", "Un type de virus informatique"], optionsEn:["A decorative sticker for a PC", "A brand new software to install", "A fix for a piece of software", "A type of computer virus"], correct:2, explanation:"Un patch est une mise à jour logicielle qui corrige des vulnérabilités ou des bugs de sécurité.", explanationEn:"A patch is a software update that fixes vulnerabilities or security bugs."},
                {id:"i_20", term:"Cheval de Troie", question:"Qu'est-ce qu'un cheval de Troie informatique ?", questionEn:"What is a computer Trojan horse?", options:["Un jeu vidéo sur l'histoire grecque", "Un antivirus gratuit mais limité", "Un malware déguisé en programme légitime", "Un navigateur web très sécurisé"], optionsEn:["A video game about Greek history", "A free but limited antivirus", "A malware disguised as a legitimate program", "A very secure web browser"], correct:2, explanation:"Un cheval de Troie se fait passer pour un logiciel légitime tout en cachant des fonctionnalités malveillantes.", explanationEn:"A Trojan horse masquerades as legitimate software while hiding malicious functionality."}
            ],
            difficile: [
                {id:"d_1", term:"Zero-day", question:"Qu'est-ce qu'une vulnérabilité zero-day ?", questionEn:"What is a zero-day vulnerability?", options:["Un correctif logiciel appliqué en urgence", "Une brèche de sécurité déjà publique", "Une faille non connue de son créateur", "Un programme malveillant très nocif"], optionsEn:["An urgently applied software fix", "An already public security breach", "A flaw unknown to its creator", "A very harmful malicious program"], correct:2, explanation:"Une vulnérabilité zero-day est une faille de sécurité inconnue du public et des développeurs.", explanationEn:"A zero-day vulnerability is a security flaw unknown to the public and developers."},
                {id:"d_2", term:"APT", question:"Que signifie APT en cybersécurité ?", questionEn:"What does APT mean in cybersecurity?", options:["Menace Persistante Avancée", "Outil de Protection Automatisé", "Technologie Anti-Phishing Performante", "Test de Pénétration d'Application"], optionsEn:["Advanced Persistent Threat", "Automated Protection Tool", "Advanced Phishing Technology", "Application Penetration Test"], correct:0, explanation:"APT (Advanced Persistent Threat) désigne une cyberattaque sophistiquée et prolongée.", explanationEn:"APT (Advanced Persistent Threat) refers to a sophisticated and prolonged cyberattack."},
                {id:"d_3", term:"SIEM", question:"Qu'est-ce qu'un système SIEM ?", questionEn:"What is a SIEM system?", options:["Gestion des infos et événements de sécurité", "Protocole d'Email Internet Simplifié", "Système d'Échange d'Identité Multiple", "Moteur d'Intégration d'Événements"], optionsEn:["Security Information and Event Management", "Simple Internet Email Protocol", "Multiple Identity Exchange System", "System Integration Event Motor"], correct:0, explanation:"SIEM collecte et analyse les logs de sécurité pour détecter les menaces.", explanationEn:"SIEM collects and analyzes security logs to detect threats."},
                {id:"d_4", term:"Honeypot", question:"Qu'est-ce qu'un honeypot en cybersécurité ?", questionEn:"What is a honeypot in cybersecurity?", options:["Un pot de miel numérique chiffré", "Un système de sauvegarde isolé", "Un système informatique servant de leurre", "Un protocole de chiffrement avancé"], optionsEn:["An encrypted digital honey pot", "An isolated backup system", "A computer system serving as a decoy", "An advanced encryption protocol"], correct:2, explanation:"Un honeypot est un système piège conçu pour attirer et étudier les attaquants.", explanationEn:"A honeypot is a trap system designed to attract and study attackers."},
                {id:"d_5", term:"DDoS", question:"Comment fonctionne une attaque DDoS ?", questionEn:"How does a DDoS attack work?", options:["Elle supprime des fichiers système", "Elle vole les mots de passe stockés", "Elle surcharge un service de requêtes", "Elle chiffre les données du serveur"], optionsEn:["It deletes system files", "It steals stored passwords", "It overloads a service with requests", "It encrypts the server's data"], correct:2, explanation:"Une attaque DDoS submerge un serveur avec un trafic massif pour le rendre indisponible.", explanationEn:"A DDoS attack overwhelms a server with massive traffic to make it unavailable."},
                {id:"d_6", term:"Buffer Overflow", question:"Qu'est-ce qu'un buffer overflow ?", questionEn:"What is a buffer overflow?", options:["Un débordement de tampon mémoire", "Une saturation du trafic réseau", "Un virus qui se propage vite", "Une faille dans un mot de passe"], optionsEn:["A memory buffer overflow", "A network traffic saturation", "A fast-spreading virus", "A flaw in a password"], correct:0, explanation:"Un buffer overflow survient quand un programme écrit plus de données qu'un tampon ne peut en contenir, pouvant mener à l'exécution de code malveillant.", explanationEn:"A buffer overflow occurs when a program writes more data than a buffer can hold, potentially leading to malicious code execution."},
                {id:"d_7", term:"PKI", question:"Qu'est-ce qu'une PKI ?", questionEn:"What is a PKI?", options:["Infrastructure à Clé Privée", "Interface de Noyau Protégée", "Infrastructure à Clé Publique", "Index de Connaissance Personnelle"], optionsEn:["Private Key Infrastructure", "Protected Kernel Interface", "Public Key Infrastructure", "Personal Knowledge Index"], correct:2, explanation:"Une PKI (Public Key Infrastructure) gère les certificats et clés cryptographiques pour sécuriser les communications.", explanationEn:"A PKI (Public Key Infrastructure) manages certificates and cryptographic keys to secure communications."},
                {id:"d_8", term:"Rainbow Table", question:"Qu'est-ce qu'une rainbow table ?", questionEn:"What is a rainbow table?", options:["Un tableau de données colorées", "Une base de données relationnelle", "Une table de hachages précalculés", "Un algorithme de tri de données"], optionsEn:["A table of colored data", "A relational database", "A table of precomputed hashes", "A data sorting algorithm"], correct:2, explanation:"Une rainbow table contient des hachages précalculés utilisés pour craquer des mots de passe par recherche inverse.", explanationEn:"A rainbow table contains precomputed hashes used to crack passwords through reverse lookup."},
                {id:"d_9", term:"SQL Injection", question:"Qu'est-ce qu'une injection SQL ?", questionEn:"What is an SQL injection?", options:["Une vaccination de base de données", "Un langage de programmation web", "Une technique d'attaque de base de données", "Un outil de sauvegarde de base de données"], optionsEn:["A database vaccination", "A web programming language", "A database attack technique", "A database backup tool"], correct:2, explanation:"L'injection SQL exploite les vulnérabilités dans les applications web pour manipuler les requêtes de base de données.", explanationEn:"SQL injection exploits vulnerabilities in web applications to manipulate database queries."},
                {id:"d_10", term:"Rootkit", question:"Qu'est-ce qu'un rootkit ?", questionEn:"What is a rootkit?", options:["Un kit d'outils de jardinage", "Un ensemble d'outils de développement", "Un malware conçu pour être furtif", "Un système de sauvegarde racine"], optionsEn:["A gardening toolkit", "A set of development tools", "A malware designed to be stealthy", "A root backup system"], correct:2, explanation:"Un rootkit est un malware furtif qui se cache profondément dans le système pour éviter la détection.", explanationEn:"A rootkit is stealthy malware that hides deep in the system to avoid detection."},
                {id:"d_11", term:"LDAP", question:"À quoi sert le protocole LDAP ?", questionEn:"What is the LDAP protocol used for?", options:["Le transfert de fichiers sécurisé", "Le chiffrement des emails pro", "L'accès à des services d'annuaire", "La navigation web optimisée"], optionsEn:["Secure file transfer", "Professional email encryption", "Accessing directory services", "Optimized web browsing"], correct:2, explanation:"LDAP (Lightweight Directory Access Protocol) permet d'accéder et de maintenir des services d'annuaire distribués.", explanationEn:"LDAP (Lightweight Directory Access Protocol) allows access to and maintenance of distributed directory services."},
                {id:"d_12", term:"XSS", question:"Qu'est-ce qu'une attaque XSS ?", questionEn:"What is an XSS attack?", options:["Script inter-site (Cross-Site Scripting)", "Système de Sécurité Étendu", "Service de Serveur Externe", "Scanner de Sécurité Extrême"], optionsEn:["Cross-Site Scripting", "eXtended Security System", "eXternal Server Service", "eXtreme Security Scanner"], correct:0, explanation:"XSS (Cross-Site Scripting) injecte du code malveillant dans des pages web vues par d'autres utilisateurs.", explanationEn:"XSS (Cross-Site Scripting) injects malicious code into web pages viewed by other users."},
                {id:"d_13", term:"Blockchain", question:"Quel est l'avantage principal de la blockchain pour la sécurité ?", questionEn:"What is the main advantage of blockchain for security?", options:["Sa vitesse de traitement élevée", "Sa grande facilité d'utilisation", "L'immutabilité des données", "Son faible coût de déploiement"], optionsEn:["Its high processing speed", "Its great ease of use", "The immutability of data", "Its low deployment cost"], correct:2, explanation:"La blockchain assure l'immutabilité des données grâce à sa structure cryptographique décentralisée.", explanationEn:"Blockchain ensures data immutability through its decentralized cryptographic structure."},
                {id:"d_14", term:"IoT Security", question:"Quel est le principal défi de sécurité avec l'IoT ?", questionEn:"What is the main security challenge with IoT?", options:["Le coût élevé d'implémentation", "La vitesse de connexion requise", "La gestion hétérogène des appareils", "La complexité de l'interface"], optionsEn:["The high implementation cost", "The required connection speed", "The heterogeneous device management", "The complexity of the interface"], correct:2, explanation:"L'IoT pose des défis de sécurité majeurs dus au grand nombre d'appareils connectés souvent mal sécurisés.", explanationEn:"IoT poses major security challenges due to the large number of connected devices that are often poorly secured."},
                {id:"d_15", term:"Forensics", question:"Qu'est-ce que l'informatique légale (forensics) ?", questionEn:"What is computer forensics?", options:["La réparation d'ordinateurs", "Le développement de logiciels", "L'investigation numérique post-incident", "La maintenance de serveurs"], optionsEn:["Computer repair", "Software development", "Post-incident digital investigation", "Server maintenance"], correct:2, explanation:"L'informatique légale consiste à collecter, analyser et présenter des preuves numériques dans un contexte juridique.", explanationEn:"Computer forensics involves collecting, analyzing and presenting digital evidence in a legal context."}
            ],
            nexus: [
                {
                    id:"n_1", term:"Attaques Microarchitecturales", 
                    question:"Quelle attaque par canal auxiliaire exploite la contention sur le planificateur de ports des CPU ?", 
                    questionEn:"Which side-channel attack exploits contention on the port scheduler in modern CPUs?", 
                    options:["Meltdown (fuite de données)", "Spectre (exécution spéculative)", "PortSmash (contention SMT)", "Rowhammer (perturbation DRAM)"], 
                    optionsEn:["Meltdown (data leakage)", "Spectre (speculative execution)", "PortSmash (SMT contention)", "Rowhammer (DRAM disturbance)"], 
                    correct:2, 
                    explanation:"PortSmash est une attaque qui exploite le SMT (Simultaneous Multithreading) pour extraire des informations en créant une contention sur les ports d'exécution partagés du processeur.", 
                    explanationEn:"PortSmash is an attack that exploits SMT (Simultaneous Multithreading) to extract information by creating contention on the processor's shared execution ports."
                },
                {
                    id:"n_2", term:"Malware Avancé", 
                    question:"À quoi sert la technique 'Heaven's Gate' pour un malware 32-bit sur un OS 64-bit ?", 
                    questionEn:"What is the 'Heaven's Gate' technique used for by 32-bit malware on a 64-bit OS?", 
                    options:["Contourner le contrôle de compte (UAC)", "Exécuter du code natif 64-bit", "Cacher des fichiers dans des flux ADS", "Persistance via détournement COM"], 
                    optionsEn:["Bypassing User Account Control (UAC)", "Executing native 64-bit code", "Hiding files in ADS streams", "Persistence via COM hijacking"], 
                    correct:1, 
                    explanation:"'Heaven's Gate' permet à un processus 32-bit de passer en mode 'long' 64-bit via un sélecteur de segment de code spécial, lui permettant d'appeler directement des API 64-bit.", 
                    explanationEn:"'Heaven's Gate' allows a 32-bit process to switch to 64-bit 'long mode' via a special code segment selector, enabling it to call 64-bit APIs directly."
                },
                {
                    id:"n_3", term:"Cryptographie Appliquée", 
                    question:"L'attaque de Bleichenbacher est une attaque par oracle qui cible quel schéma de chiffrement ?", 
                    questionEn:"A Bleichenbacher's attack is a padding oracle attack that targets which encryption scheme?", 
                    options:["Le mode AES-CBC (symétrique)", "L'algorithme de signature DSA", "Le chiffrement RSA PKCS#1 v1.5", "L'échange de clés Diffie-Hellman"], 
                    optionsEn:["The AES-CBC mode (symmetric)", "The Digital Signature Algorithm (DSA)", "RSA encryption with PKCS#1 v1.5", "The Diffie-Hellman key exchange"], 
                    correct:2, 
                    explanation:"L'attaque de Bleichenbacher de 1998 exploite la manière dont les serveurs signalent les erreurs de remplissage PKCS#1 v1.5 pour déchiffrer progressivement un ciphertext RSA.", 
                    explanationEn:"The 1998 Bleichenbacher's attack exploits how servers report PKCS#1 v1.5 padding errors to progressively decrypt an RSA ciphertext."
                },
                {
                    id:"n_4", term:"Sécurité Cloud Native", 
                    question:"Une fonction de sécurité clé d'un service mesh (ex: Istio) dans Kubernetes est de :", 
                    questionEn:"A key security function of a service mesh (e.g., Istio) in Kubernetes is to:", 
                    options:["Analyser le code statique des conteneurs", "Gérer le routage du trafic Ingress", "Chiffrer automatiquement le trafic inter-pods", "Fournir un stockage persistant chiffré"], 
                    optionsEn:["Perform static code analysis on containers", "Manage Ingress traffic routing", "Automatically encrypt all inter-pod traffic", "Provide encrypted persistent storage"], 
                    correct:2, 
                    explanation:"Un service mesh applique le mTLS (mutual TLS) pour chiffrer et authentifier automatiquement toutes les communications entre les services (pods) au sein du cluster.", 
                    explanationEn:"A service mesh enforces mTLS (mutual TLS) to automatically encrypt and authenticate all communications between services (pods) within the cluster."
                },
                {
                    id:"n_5", term:"Sécurité des SI Industriels", 
                    question:"Dans un environnement SCADA, quel protocole est une cible privilégiée pour des attaques MitM ?", 
                    questionEn:"In a SCADA environment, which protocol is a prime target for MitM attacks?", 
                    options:["DNP3 (avec authentification)", "PROFINET (temps-réel)", "Modbus TCP (sans sécurité native)", "OPC UA (sécurité intégrée)"], 
                    optionsEn:["DNP3 (with authentication)", "PROFINET (real-time)", "Modbus TCP (no native security)", "OPC UA (integrated security)"], 
                    correct:2, 
                    explanation:"Modbus TCP, un protocole très répandu dans les systèmes industriels, a été conçu sans aucune fonction de sécurité, le rendant vulnérable aux écoutes et aux injections de commandes.", 
                    explanationEn:"Modbus TCP, a widespread protocol in industrial systems, was designed without any security features, making it vulnerable to eavesdropping and command injection."
                },
                {
                    id:"n_6", term:"Threat Hunting", 
                    question:"Quel langage de requête est utilisé pour le threat hunting dans Microsoft Sentinel ?", 
                    questionEn:"Which query language is used for threat hunting in Microsoft Sentinel?", 
                    options:["SPL (utilisé par Splunk)", "YARA-L (utilisé par Chronicle)", "KQL (Kusto Query Language)", "Lucene (utilisé par Elastic)"], 
                    optionsEn:["SPL (used by Splunk)", "YARA-L (used by Chronicle)", "KQL (Kusto Query Language)", "Lucene (used by Elastic)"], 
                    correct:2, 
                    explanation:"KQL est le langage utilisé pour interroger les données de log et d'événements dans l'écosystème de sécurité de Microsoft, permettant une investigation approfondie.", 
                    explanationEn:"KQL is the language used to query log and event data across the Microsoft security ecosystem, enabling deep investigation."
                },
                {
                    id:"n_7", term:"Sécurité Automobile", 
                    question:"Envoyer un message UDS avec le service ID 0x27 sur un bus CAN vise généralement à :", 
                    questionEn:"Sending a UDS message with service ID 0x27 on a CAN bus typically aims to:", 
                    options:["Lire le numéro de série du véhicule", "Déverrouiller un ECU pour accès avancé", "Déclencher l'alarme à distance", "Diffuser un faux signal GPS au système"], 
                    optionsEn:["Read the vehicle's serial number", "Unlock an ECU for advanced access", "Trigger the alarm remotely", "Broadcast a fake GPS signal to the system"], 
                    correct:1, 
                    explanation:"Le service 0x27 est un mécanisme de type 'challenge-response' pour obtenir un niveau d'accès de sécurité supérieur sur un ECU, souvent nécessaire avant des opérations sensibles comme le flashage.", 
                    explanationEn:"Service 0x27 is a challenge-response mechanism to gain a higher security access level on an ECU, often required before sensitive operations like flashing."
                },
                {
                    id:"n_8", term:"Vérification Formelle", 
                    question:"En vérification formelle, quelle méthode est adaptée pour prouver des propriétés sur des systèmes à états infinis ?", 
                    questionEn:"In formal verification, which method is suited for proving properties on infinite-state systems?", 
                    options:["Le Model Checking (états finis)", "L'Exécution Symbolique (chemins)", "L'Interprétation Abstraite (domaines)", "Le Fuzzing (tests aléatoires)"], 
                    optionsEn:["Model Checking (finite states)", "Symbolic Execution (paths)", "Abstract Interpretation (domains)", "Fuzzing (random testing)"], 
                    correct:2, 
                    explanation:"L'interprétation abstraite analyse le comportement d'un programme en se basant sur des approximations sûres (abstractions) de ses états, ce qui permet de raisonner sur des domaines infinis.", 
                    explanationEn:"Abstract interpretation analyzes a program's behavior based on safe approximations (abstractions) of its states, making it possible to reason about infinite domains."
                },
                {
                    id:"n_9", term:"Technologie de Déception", 
                    question:"Dans une architecture de déception, quel est le but principal d'un 'bread-crumb' (miette de pain) ?", 
                    questionEn:"In a deception architecture, what is the main purpose of a 'bread-crumb'?", 
                    options:["Ralentir la machine de l'attaquant", "Leurrer un attaquant vers un honeypot", "Chiffrer les données de l'attaquant", "Identifier les outils de l'attaquant"], 
                    optionsEn:["Slow down the attacker's machine", "Lure an attacker towards a honeypot", "Encrypt the attacker's data", "Fingerprint the attacker's tools"], 
                    correct:1, 
                    explanation:"Les 'bread-crumbs' sont de faux artefacts (ex: fausses clés SSH, mots de passe en cache) laissés sur de vrais systèmes pour attirer les attaquants vers des leurres (honeypots) où ils peuvent être observés.", 
                    explanationEn:"'Bread-crumbs' are fake artifacts (e.g., fake SSH keys, cached passwords) left on real systems to lure attackers towards decoys (honeypots) where they can be observed."
                },
                {
                    id:"n_10", term:"Cryptographie Avancée", 
                    question:"L'avantage principal d'un schéma de chiffrement préservant le format (FPE) est de :", 
                    questionEn:"The main advantage of a format-preserving encryption (FPE) scheme is to:", 
                    options:["Offrir de meilleures performances que l'AES", "Être résistant aux ordinateurs quantiques", "Chiffrer des données sans altérer leur format", "Générer des textes chiffrés plus courts"], 
                    optionsEn:["Offer better performance than AES", "Be resistant to quantum computers", "Encrypt data without altering its format", "Generate shorter ciphertexts"], 
                    correct:2, 
                    explanation:"Le FPE permet de chiffrer des données structurées (ex: numéro de carte de crédit, de sécurité sociale) en un ciphertext qui a le même format, ce qui simplifie l'intégration dans les systèmes existants.", 
                    explanationEn:"FPE allows encrypting structured data (e.g., credit card number, social security number) into a ciphertext that has the same format, simplifying integration into legacy systems."
                }
            ]
        };
